### ISSUE TITLE
Authentifizierung ändern

### ISSUE THREAD

**Issue by DonSchado** [erdnusskeks/veganapp#1]
Im Application Controller hatten wir ja letztens eine simple Passwortabfrage hinzugefügt.
https://github.com/erdnusskeks/veganapp/blob/master/app/controllers/application_controller.rb#L3

War damals als der Code nicht öffentlich war kein Problem, ab jetzt könnte theoretisch aber jeder der sowohl das Repo als auch die Heroku URL kennt, sich Zugang verschaffen.

Ist im Moment vermutlich nicht das riesen Problem, sollten wir aber bald angehen. 
Wenn du schonmal selber schauen möchtest, es gibt hier mehrere Möglichkeiten. 

Wie die momentane Lösung funktioniert kannst du nochmal hier anschauen:
http://railscasts.com/episodes/270-authentication-in-rails-3-1
da geht Ryan auch auf eine bessere Lösung mit einem User Model ein. 
(den SSL Teil kannst du ignorieren)

Ähnlich macht er das auch hier:
http://railscasts.com/episodes/250-authentication-from-scratch
btw. hier der Code für die revised Episode (Video benötigt ein PRO Abo) 
https://github.com/ryanb/railscasts-episodes/tree/master/episode-250/revised

Eine andere Lösung die weniger Code benötigt, aber vielleicht auch komplizierter zu verstehen ist, wäre Benutzer und Password in sogenannte Environment Variables zu schreiben. (Sowohl bei dir local als auch auf Heroku)
mehr zu dem Thema findest du z.B. hier: http://railsapps.github.io/rails-environment-variables.html
und hier: https://devcenter.heroku.com/articles/config-vars
So hatte zumindest die Daniela das Problem mit ihrem Zeit Api Key gelöst: 
https://github.com/elaOnMars/Artikelsauger#set-up-your-personal-zeit-api-key

Sooo viele Hausaufgaben!
Viel Spaß und bei Fragen immer fragen. ;)
LG

**Comment by DonSchado** [comment]
wollen wir die App nochmal frisch machen? oder still und leise sterben lassen?

**Comment by erdnusskeks** [comment]
Nein, nicht sterben lassen!

Vielleicht finden wir ja am Wochenende bisschen Zeit, um daran zu arbeiten.
Sonst sehr gerne übernächste Woche - dann bin ich frisch aus dem Urlaub
zurück und hungrig auf Code. ; )

Wir sehen uns in Kalk!

Liebe Grüße
Denise

2014-09-25 9:46 GMT+02:00 Marco notifications@github.com:

**Comment by erdnusskeks** [comment]
Hallo Marco,

sollen wir uns diese Woche mal an die App heranwagen?
Ich hätte morgen oder Freitag Zeit (jeweils ab 17.00 Uhr).
Wann ist es Dir am liebsten? Passt 17.00 Uhr oder besser später?

Liebe Grüße
Denise

Am 25. September 2014 11:05 schrieb Denise Schynol <
erdnusskeks@googlemail.com>:

**Comment by DonSchado** [comment]
Hi Denise, 

cool, morgen 17:00! :)

LG
Marco

Am 20.10.2014 um 11:55 schrieb Denise notifications@github.com:

**Comment by erdnusskeks** [comment]
Klasse, dann bis morgen!

Liebe Grüße
Denise

Am 20. Oktober 2014 12:02 schrieb Marco notifications@github.com:
