### ISSUE TITLE
change README

### ISSUE THREAD

**Issue by DonSchado** [erdnusskeks/veganapp#2]
benenne die README.rdoc Datei um in README.md. (d.h. Markdown)
Lösche den kompletten Inhalt und schreib einfach 1-2 Sätze was die App macht/kann.

**Comment by erdnusskeks** [comment]
Mache ich das lokal, also mit meinem Editor, und ändere es dann in GitHub, also übers Terminal?

**Comment by DonSchado** [comment]
genau! in sublime ändern. dann im terminal (mit git) einen commit machen und zu origin master pushen. :)

**Comment by erdnusskeks** [comment]
Ok, was habe ich falsch gemacht?

Marvin:vegan-app erdnusskeks$ git push -u origin master
Warning: Permanently added the RSA host key for IP address '192.30.252.131' to the list of known hosts.
To git@github.com:erdnusskeks/veganapp.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'git@github.com:erdnusskeks/veganapp.git'
To prevent you from losing history, non-fast-forward updates were rejected
Merge the remote changes (e.g. 'git pull') before pushing again.  See the
'Note about fast-forwards' section of 'git push --help' for details.

**Comment by DonSchado** [comment]
das bedeutet das das Repository auf Github Änderungen hat, die du local noch nicht hast. 
Die Änderungen kannst du mit einem  `git pull` holen.

Wenn es dann keine Konflikte gibt. Einfach danach nochmal pushen. 
Wenn es einen Konflikt gibt, nochmal schreiben! :)

**Comment by erdnusskeks** [comment]
Pull klappt nicht. Ich weiß nicht wie man das hier macht: fix them up in the work tree...

Marvin:vegan-app erdnusskeks$ git pull
U   .gitignore
A   README.rdoc
Pull is not possible because you have unmerged files.
Please, fix them up in the work tree, and then use 'git add/rm <file>'
as appropriate to mark resolution, or use 'git commit -a'.

**Comment by DonSchado** [comment]
ja, du hast lokale Änderungen die du noch nicht committed hast. :) 
Hast du das Git Tutorial gemacht? 

ansonsten versuch mal folgendes:

`git status`

und guck mal was da alles rumliegt.

mit `git add .` fügst du _alle_ Änderungen der Staging Area hinzu.

dann committen `git commit -am "here are my new changes"`

pullen mit `git pull origin master` 

und pushen `git push origin master`
